name = "no_overlap_edges"
description = "A simple base grid with boundary conditions."
time_span = [0, 250]
solver = "BDF"

[starting_condition]
type = "gaussian"
height = 1000
centre = 2
width = 0.05
base = 0

[grids]

[grids.base]
left_pos = 0
right_pos = 4
dx = 0.01
alpha = 0.005
left_boundary = "CONSTANT"
right_boundary = "CONSTANT"
left_boundary_value = 0
right_boundary_value = 0
interface_width = nan
num_fringe_cells = nan
