time_span = [0, 2000]
solver = "Radau"

[starting_condition]
type = "gaussian"
height = 1000
centre = 0.5
width = 0.05
base = 0

[grids]

[grids.base]
left_pos = 0
right_pos = 1
dx = 0.01
alpha = 1
left_boundary = "PERIODIC"
right_boundary = "PERIODIC"
interface_width = nan
num_fringe_cells = nan

[grids.overlap]
left_pos = 0.45
right_pos = 0.6
dx = 0.005
alpha = 1
left_boundary = "WALL"
right_boundary = "WALL"
interface_width = 0.03
num_fringe_cells = 1
