name = "test sweep"
description = "Simple sweep of the cell widths for testing"
solvers = ["Radau"]

[parameters]
[parameters.dx]

[parameters.dx.base]
type = "range"
start = 0.01
end = 0.0001
number = 100

[parameters.dx.overlap]
type = "ratio"
grid = "base"
factor = 0.5
